name: "CLaaT setup"

description: |
  Setup CLaat CLI (Go module).

inputs:
  claat-version:
    description: |
      claat version.
      Default is latest
    required: false
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Check Runner OS
      if: ${{ runner.os != 'Linux' }}
      shell: bash
      run: |
        echo "::error title=⛔ error hint::Support Linux Only"
        exit 1

    - name: Get go.sum from claat repo
      shell: bash
      continue-on-error: true
      run: |
        wget https://raw.githubusercontent.com/googlecodelabs/tools/main/claat/go.sum

    - name: Setup Go v1.18 (compatible with claat)
      uses: actions/setup-go@v5
      with:
        go-version: "1.18"

    - name: Deletet go.sum
      shell: bash
      continue-on-error: true
      run: |
        rm go.sum

    - name: Export Go bin to all steps
      id: go-env
      shell: bash
      run: |
        echo "::group::Export Go bin to all steps"
        go version
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        echo "go bin exported."
        echo "::endgroup::"


    - name: Setup claat (latest)
      shell: bash
      env:
        VERSION: ${{ inputs.claat-version }}
      run: |
        echo "::group::Setup claat (latest)"
        mkdir -p $(go env GOPATH)/bin
        go install github.com/googlecodelabs/tools/claat@$VERSION
        claat version
        echo "::endgroup::"
