name: 'Test'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  demo-claat-action:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    env:
      GDOC_ID: 1al07Cg0AUmvb4FXd35KCQT1VvdRU7cGlrEEMdKqgo1I
      GA_ID: "UA-3295395-7"
      GA_ID_V4: "G-E0H6JSF2N3"
      OUTPUT_PATH: test
      JSON_FILE: assets/codelabs.json
    steps:
      - uses: actions/checkout@v4

      - name: Generate Oauth2 token
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          access_token_scopes: "https://www.googleapis.com/auth/drive.readonly"
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_CREDS }}"

      - name: claat (single document)
        uses: ./
        with:
          auth: ${{ steps.auth.outputs.access_token }}
          source: ${{env.GDOC_ID}}
          codelabs-path: ${{env.OUTPUT_PATH}}
          gaid: ${{env.GA_ID}}
          ga4id: ${{env.GA_ID_V4}}

      - name: claat (single document - test min inputs - gdoc)
        uses: ./
        with:
          auth: ${{ steps.auth.outputs.access_token }}
          source: ${{env.GDOC_ID}}

      - name: claat (single document - test min inputs - md)
        uses: ./
        with:
          source: "assets/md/index.md"

      - name: claat (single document - test min inputs - all)
        uses: ./
        with:
          auth: ${{ steps.auth.outputs.access_token }}
          source: ${{env.GDOC_ID}}
          format: all

      - name: claat (single document - test min inputs - environment)
        uses: ./
        with:
          auth: ${{ steps.auth.outputs.access_token }}
          source: ${{env.GDOC_ID}}
          environment: kiosk

      - name: claat (codelabs.json)
        uses: ./
        with:
          auth: ${{ steps.auth.outputs.access_token }}
          source: ${{env.GDOC_ID}}  
          codelabs-path: ${{env.OUTPUT_PATH}}
          codelabs-json: ${{env.JSON_FILE}}

      # update command without sources will scan current dir for codelab.json
      # test exported codelabs from previous step
      # codelabs-path used to change working directory (claat flags are ignored in update)
      # check 'claat help'
      - name: claat (codelabs.json - update)
        uses: ./
        with:
          auth: ${{ steps.auth.outputs.access_token }} 
          command: 'update'
          codelabs-path: assets
